version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/circleci-gcp-node10

    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
            docker build -f Dockerfile -t circleci-gcp-node10 .
      - deploy:
          name: Push Docker image
          command: |
              login="docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS"
              ${login}
              docker tag circleci-gcp-node10 easymetrics/circleci-gcp-node10
              docker push easymetrics/circleci-gcp-node10